# Build stage
FROM rust:1.83 AS builder

WORKDIR /build

# Copy all source code
COPY Cargo.toml .
COPY src src

# Build the application
RUN cargo build --release

# Runtime stage
FROM debian:bookworm-slim

# Copy the binary from the builder
COPY --from=builder /build/target/release/cddns /bin/cddns

ENTRYPOINT [ "cddns" ]
